version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    extra_hosts: 
      - "host.docker.internal:host-gateway"